// tailwind.config.js
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html"
  ],
  theme: {
    extend: {
      fontFamily: {
        'mono': ['ui-monospace', 'SFMono-Regular', 'Monaco', 'Consolas', 'Liberation Mono', 'Menlo', 'monospace'],
        'sans': ['ui-sans-serif', 'system-ui', 'sans-serif'],
        'serif': ['ui-serif', 'Georgia', 'Cambria', 'Times New Roman', 'Times', 'serif']
      },
      letterSpacing: {
        'widest': '0.25em',
      },
      animation: {
        'pulse': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'spin': 'spin 1s linear infinite',
        'bounce': 'bounce 1s infinite',
      }
    },
  },
  plugins: [
    require("daisyui")
  ],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "#000000",
          "primary-focus": "#000000", 
          "primary-content": "#ffffff",
          "secondary": "#374151",
          "secondary-focus": "#1f2937",
          "secondary-content": "#ffffff",
          "accent": "#6b7280",
          "accent-focus": "#4b5563",
          "accent-content": "#ffffff",
          "neutral": "#9ca3af",
          "neutral-focus": "#6b7280",
          "neutral-content": "#ffffff",
          "base-100": "#ffffff",
          "base-200": "#f9fafb",
          "base-300": "#e5e7eb",
          "base-content": "#111827",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#10b981",
          "success-content": "#ffffff", 
          "warning": "#f59e0b",
          "warning-content": "#000000",
          "error": "#ef4444",
          "error-content": "#ffffff",
        },
      },
      {
        dark: {
          "primary": "#ffffff",
          "primary-focus": "#e5e7eb",
          "primary-content": "#000000",
          "secondary": "#d1d5db",
          "secondary-focus": "#9ca3af",
          "secondary-content": "#000000",
          "accent": "#6b7280",
          "accent-focus": "#4b5563",
          "accent-content": "#ffffff",
          "neutral": "#4b5563",
          "neutral-focus": "#374151",
          "neutral-content": "#ffffff",
          "base-100": "#1f2937",
          "base-200": "#111827",
          "base-300": "#0f172a",
          "base-content": "#f9fafb",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#10b981",
          "success-content": "#ffffff",
          "warning": "#f59e0b", 
          "warning-content": "#000000",
          "error": "#ef4444",
          "error-content": "#ffffff",
        },
      },
      {
        black: {
          "primary": "#ffffff",
          "primary-focus": "#e5e7eb",
          "primary-content": "#000000", 
          "secondary": "#d1d5db",
          "secondary-focus": "#9ca3af",
          "secondary-content": "#000000",
          "accent": "#6b7280",
          "accent-focus": "#4b5563", 
          "accent-content": "#ffffff",
          "neutral": "#374151",
          "neutral-focus": "#1f2937",
          "neutral-content": "#ffffff",
          "base-100": "#000000",
          "base-200": "#0a0a0a", 
          "base-300": "#1a1a1a",
          "base-content": "#ffffff",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#10b981", 
          "success-content": "#ffffff",
          "warning": "#f59e0b",
          "warning-content": "#000000",
          "error": "#ef4444",
          "error-content": "#ffffff",
        },
      },
      {
        luxury: {
          "primary": "#000000",
          "primary-focus": "#000000",
          "primary-content": "#fffbeb",
          "secondary": "#92400e",
          "secondary-focus": "#78350f",
          "secondary-content": "#fffbeb", 
          "accent": "#d97706",
          "accent-focus": "#b45309",
          "accent-content": "#fffbeb",
          "neutral": "#a16207",
          "neutral-focus": "#92400e",
          "neutral-content": "#fffbeb",
          "base-100": "#fffbeb",
          "base-200": "#fef3c7",
          "base-300": "#fde68a",
          "base-content": "#92400e",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#10b981",
          "success-content": "#ffffff",
          "warning": "#f59e0b",
          "warning-content": "#000000",
          "error": "#ef4444", 
          "error-content": "#ffffff",
        },
      },
      {
        corporate: {
          "primary": "#000000",
          "primary-focus": "#000000",
          "primary-content": "#f8fafc",
          "secondary": "#334155",
          "secondary-focus": "#1e293b", 
          "secondary-content": "#f8fafc",
          "accent": "#64748b",
          "accent-focus": "#475569",
          "accent-content": "#f8fafc",
          "neutral": "#64748b",
          "neutral-focus": "#475569",
          "neutral-content": "#f8fafc",
          "base-100": "#f8fafc",
          "base-200": "#f1f5f9",
          "base-300": "#e2e8f0",
          "base-content": "#0f172a",
          "info": "#3b82f6",
          "info-content": "#ffffff",
          "success": "#10b981",
          "success-content": "#ffffff",
          "warning": "#f59e0b",
          "warning-content": "#000000",
          "error": "#ef4444",
          "error-content": "#ffffff",
        },
      }
    ],
  },
}