services:
  - type: web
    name: confession-app
    env: node
    plan: free
    buildCommand: |
      echo "Installing dependencies..."
      npm install
      echo "Building frontend..."
      cd frontend && npm install && npm run build
      echo "Build complete!"
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: confession-db
          property: connectionString
      - key: CLERK_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        fromService:
          type: web
          name: confession-app
          property: host
    autoDeploy: true
